name: "å‘å¸ƒæ–°åŒ…"

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish-to-pub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: ğŸ”§ Setup Dart SDK
        uses: dart-lang/setup-dart@v2.12.3 # setups dart sdk on this machine
      - name: ğŸš€Publish
        uses: RatakondalaArun/pub.dev-cd@v1
        with:
          creditionals: ${{secrets.PUB_CREDITIONALS}}
          # package_path: packages/subpackage
